version: "3"

services:

  proxy:
    image: nginx
    networks:
      default:
        aliases:
          - anniversary-local.com
    volumes:
      - ./proxy/custom.conf:/etc/nginx/conf.d/custom.conf
      - ./proxy/ssl-cert-snakeoil.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - ./proxy/ssl-cert-snakeoil.key:/etc/ssl/private/ssl-cert-snakeoil.key
      - ./log/proxy/nginx/:/var/log/nginx
    links:
      - anniversary
    ports:
      - "${PROXY_HTTP_PORT}:80"
      - "${PROXY_HTTPS_PORT}:443"
    env_file: .env

  anniversary:
    build:
      context: anniversary
    volumes:
      - "${ANNI_SRC}:/var/www/html/anniversary"
      - ./log/anniversary/httpd:/var/log/httpd/
    links:
      - db
      - selenium
    env_file: .env

  db:
    image: mysql:5.5
    ports:
      - ${MYSQL_HOST_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file: .env

  selenium:
    image: selenium/standalone-chrome:3.0.1-fermium
    volumes:
      - /dev/shm:/dev/shm
      - ./input_data:/input_data
    ports:
      - "${SELENIUM_SERVER_PORT}:4444"
      - "${SELENIUM_VNC_PORT}:5900"
    env_file: .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 6789:8080

volumes:
  kaltura-volume: {}
  kaltura-nginx-volume: {}
  datastore: {}
networks:
  default: {}
